version: '3.8'

services:

  mysql_ps_db:
    image: mysql:8.0
    container_name: mysql_ps_db
    environment:
      MYSQL_ROOT_PASSWORD: mIXmKg2kzePV
      MYSQL_PASSWORD: mIXmKg2kzePV
      MYSQL_DATABASE: ps_db
    ports:
      - "3307:3306"
    networks:
      - mysql_network
    volumes:
      - mysql_ps_db_data:/var/lib/mysql

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_ps_db_data:
    driver: local