spring:
  application:
    name: PS_employee
  datasource:
    url:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/ps_db
    username: root
    password: mIXmKg2kzePV
  flyway:
    enabled: false

ps:
  app:
    version: 102

firebase:
  serviceAccount: classpath:protection-station-2-firebase-adminsdk-fpvj7-26742d7b86.json